######################################################################
# Automatically generated by qmake (2.01a) Sun Jan 2 17:54:53 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += ngccat.cpp
